var min_bet = 0.000001,
    bigtime_bet = 0.0001,
    max_bet = null,
    multiplier = 2, 
    minutes_to_play = 15,
    rally = {}, 
    rally_bigtime = 5,
    rally_bets = 11, 
    rally_max = rally_bigtime + rally_bets,
    big_win_usd = 2,
    current_bet = min_bet,
    bet_interval,
    currency_interval,
    conversion_rate = 179,
    fx_dings = [],
    fx_jackpots = [],
    fx_aww;
